### PR TITLE
Adding the world's personal data to IPFS

### PR DESCRIPTION
**Pull request by andrewxhill**

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
Thanks for proposing this @andrewxhill! 

We're going to start working on sessions and schedule planning in earnest next week. Based on the current sketch of the schedule, I recommend preparing a 5-minute project introduction/update about textile.io that we can put into one of the rapid-fire "project updates" sessions we're planning for Day 1 and Day 2 of the Meeting.  If your full 30-minute session doesn't make it into the schedule for the first 2 days, plan to pitch it as a session for the unconference in Day 3. (Everyone will pitch and vote on unconference sessions at the end of Day 2)

**Comment by flyingzumwalt** [comment]
More info about the sessions of project updates: https://github.com/ipfs/developer-meetings/pull/4

**Comment by andrewxhill** [comment]
Sounds great! thanks

**Comment by daviddias** [comment]
@andrewxhill you currently have a lighting talk scheduled for Tuesday -- https://github.com/ipfs/developer-meetings/blob/master/sessions/LIGHTING_TALKS.md -- and this session for the Unconf Wednesday. Does this match what you were planning for? I'm merging this PR to get things tidy but let me know if you prefer to just do one of the sessions.

**Comment by andrewxhill** [comment]
Okay great, probably the lightening talk is plenty, I can get all the core pieces in there and then we can save the unconf time for topics that are popular tomorrow/tuesday, I'm sure there will be quite a few.

**Pull request merged**
