### PR TITLE
Add outcome of the GraphSync Deep-Dive

### PR DESCRIPTION
**Pull request by vmx**

### CODE REVIEW

**Comment by daviddias** [comment]
@vmx can you resolve the merge conflicts?

**Comment by vmx** [comment]
@daviddias Sure. Just out of curiosity: Why are all directories now screaming all uppercase? I personally find lowercase easier to read and navigate on a terminal.

**Comment by vmx** [comment]
@daviddias I don't have push access.

**Comment by vmx** [comment]
@daviddias  You wouldn't need to do a rename (you still have a conflict). You would just cherry pick the original commit on top of master and then do a force push.

**Pull request merged**
