### PR TITLE
Session to Discuss Switch to Base32 and the Handling of CIDv0.

### PR DESCRIPTION
**Pull request by kevina**
Please let me know if this is appropriate for this conference.

I am not a core developer so I am not 100% aware of all the issues, but I am involved enough to be willing to take the lead in the session to help push this forward.

If this is something we want to do I will put more time into flushing out the agenda.  I am thinking the use of a whiteboard to lay out all the outstanding issues will be the best way forward.  I can prepare notes ahead of time.

### CODE REVIEW

**Comment by kyledrake** [comment]
This is a very important session. There will not be case sensitive support in the mozilla/libdweb, case sensitive encoding will not work with web browsers. It's crucial that we make this final and move forward with it.

**Comment by lidel** [comment]
Count me in as well! I mentioned this need in Lisbon last month, but I agree we should be more active in pushing this: I am thinking about making the switch one of [Key Results for Q3 for Web Browsers WG](https://github.com/ipfs/in-web-browsers/issues/85).

A session could be a good opportunity to gather people around and:
- identify blockers/remaining work across the ecosystem, eg:
  - changing defaults in js-ipfs, go-ipfs
  - support in libs (CIDv1 defaults,  base32, conversion between old and new), docs
- create a rough timeline for making the switch happen
  - i feel we should aim to be done with/ready to switch by the end of Q3

**Comment by kevina** [comment]
@whyrusleeping would you consider this a deep dive session?

**Comment by whyrusleeping** [comment]
Maybe? It's more of a 'how are we going to do this?' sort of session.

**Comment by kevina** [comment]
Yeah, so I am not sure where it belongs, but a lot of people want this and I will be able to do the work once the key decisions are made and the technical problems solved.

**Comment by flyingzumwalt** [comment]
We've outlined two different formats that you might want to use for this -- [deep dives](https://github.com/ipfs/developer-meetings/tree/master/sessions/deep-dive) and [poster making](https://github.com/ipfs/developer-meetings/tree/master/sessions/poster-making). If you had to choose one of these, which would be more useful?

I suggest using a poster session to gather all the information, references, a list of options/suggestions, etc. Then you can pitch an unconf session where you go deeper into it on wednesday, using the info from the poster session as a starting point.

**Comment by kevina** [comment]
Okay.  As long as the key people are there as outlined in the proposal let's go with the poster session.  I am afraid I won't be able to put much time (if any) until this until Saturday or Sunday as my flight is leaving today.

**Comment by kevina** [comment]
Since I am in Berlin now, let me know what if anything I need to do to get this accepted.

**Comment by lidel** [comment]
Live notes for Deep Dive about Base32:
https://hackmd.io/PZCWvHfWR0-XTufiDrRGsg?edit

cc @alanshaw @magik6k @kevina @kyledrake @Kubuxu @whyrusleeping @olizilla  @lgierth

**Pull request merged**
